version: '2.4'
services:
  challenge-db:
    image: postgres:14.0
    container_name: challenge-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=challenge-db
      - POSTGRES_USER=challenge
      - POSTGRES_PASSWORD=challenge
    ports:
      - "7078:5432"
    volumes:
      - ${DB_DATA_PATH:-../../../challenge-sl-db/data}:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    mem_limit: 128m

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    mem_limit: 128m
