version: '3.1'
services:
  challenge-db:
    image: postgres:14.0
    container_name: challenge-db
    restart: unless-stopped
    networks:
      - challenge-db-net
    environment:
      - POSTGRES_DB=challenge-db
      - POSTGRES_USER=challenge
      - POSTGRES_PASSWORD=challenge
    ports:
      - "7078:5432"
    volumes:             
      - ${DB_DATA_PATH:-../../../challenge-sl-db/data}:/var/lib/postgresql/data
networks:
    challenge-db-net:
        ipam:
            driver: default
